allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - react
  - react-dom
  - next
  - "@next/*"
  - eslint-config-next